server:
  port: 8082

spring:
  application:
    name: borrow-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:  # 如果不指定命名空间会默认注册到public里面去 如果没有指定分组 会注册到DEFAULT_GROUP
      server-addr: localhost:8848  # 指定服务注册地址
      username: nacos
      password: nacos
      discovery:
        namespace: 0245d1ab-5611-486e-8444-957bebab6d78   # 若是不指定，默认就是public
        group: BOOK_GROUP   # 若是不指定，默认是DEFAULT_GROUP
        service: borrow-service   # 默认使用的是spring.application.name，这里可以进行指定

#控制台打印sql(默认不会有打印sql语句)
mybatis-plus:
  mapper-locations: classpath*:/mapperxxx/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 1、file配置
# seata配置
#seata:
#  service:
#    vgroup-mapping:
#      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default集群
#      # 这个很关键，一定要配置对，不然会找不到服务
#      borrow-service-seata-service-group: default
#    grouplist:
#      default: localhost:8868

# 2、nacos模式
seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      # 使用Seata的命名空间，这样才能正确找到Seata服务，由于组使用的是SEATA_GROUP，配置默认值就是，就不用配了
      namespace: c30eb1d8-8e49-4b5d-beca-b1bf9479e94a
      username: nacos
      password: nacos
  # 配置
  config:
    type: nacos
    nacos:
      namespace: c30eb1d8-8e49-4b5d-beca-b1bf9479e94a
      username: nacos
      password: nacos